### ISSUE TITLE
ClusterNumber  of -1?

### ISSUE THREAD

**Issue by ammaraziz** [niemasd/TreeCluster#1]
Hi,

Thank you for developing TreeCluster. When performing clustering, what does a ClusterNumber of `-1` describe?

Thanks,

Ammar

**Comment by niemasd** [comment]
Thanks for using it! All leaves given a cluster of -1 are *singletons*, meaning they did not cluster with any other leaves (i.e., each leaf with a cluster of -1 is in its own cluster)

**Comment by ammaraziz** [comment]
Thank you for the quick reply. That makes sense. 

I've been reading the clustering methods available and to be honest the advantages/disadvantages of each method and their use-case is not clear to me. It would be fantastic if you can provide more information and examples of when a clustering method is appropriate to use (or more advantageous). 

The publication does have a few working examples, but skimming through publication I notice there's a disconnect between the naming of clustering methods mentioned in the paper vs the github README. For example, `Max-diameter min-cut partitioning` referred to in the paper on HIV clustering is which clustering method? I'm guessing `Max Clade`. I do notice the paper suggests that the best clustering methods are `Max-diameter` and `Sum-length` (which I'm guessing are are `Max-Clade` and `Sum Branch Clade` respectively)

I am working on influenza virus, so HIV example is a very useful reference.

Thank you,

Ammar

**Comment by ammaraziz** [comment]
Apologies, maybe I should open another issue? 

I appreciate all your help, thank you!

**Comment by niemasd** [comment]
Woops, sorry for the premature close :-)

Yes, there is indeed some slight disconnect between the naming conventions in the paper and those in the README; I should fix those.

"Max-diameter" is generally referring to the "Max" methods (the maximum pairwise distance in each cluster must be at most *t*): "Max Clade" (which requires clusters to define clades in the tree) and "Max" (which does *not* require clusters to define clades in the tree)

"Sum-length" is generally referring to the "Sum Branch" methods (the sum of the branch lengths in each cluster must be at most *t*): "Sum Branch Clade" (which requires clusters to define clades in the tree) and "Sum Branch" (which does *not* require clusters to define clades in the tree)

**Comment by tkdspace** [comment]
Thank you, super helpful.

**Comment by niemasd** [comment]
Glad to help! I'll close this for now, but feel free to reopen or create a new issue if you have any further questions :-)
