### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by J-Calvelo** [niemasd/TreeCluster#5]
Hello, sorry for the inconvenience but I'm having issues installing TreeCluster. After running "sudo pip install treecluster" I'm getting the following error.
```
File "/usr/local/bin/TreeCluster.py", line 213
    print("%s;" % root.newick(), file=stderr)
                                     ^
SyntaxError: invalid syntax
```
I'm using phython Python 3.8.6 | packaged by conda-forge.
Thanks

**Comment by niemasd** [comment]
Thanks for reaching out! Are you certain this is running in a Python 3 environment? The syntax error it's complaining about (passing `file=` to the `print` function) is a Python 2 issue (the `print` function of Python 3 supports this syntax). I think your environment may be trying to run `TreeCluster.py` using Python 2, [which is not supported](https://www.python.org/doc/sunset-python-2/)

**Comment by niemasd** [comment]
If you attempted to install using `sudo pip install treecluster`, my best guess is that the `pip` executable in your `PATH` is part of a Python 2 environment. I would recommend doing the following:
* Uninstall TreeCluster: `sudo pip uninstall treecluster`
* Find the full path of the `pip` executable that belongs to your conda's Python 3 environment
* Run `<YOUR_CONDA_PIP_PATH> install treecluster`

**Comment by J-Calvelo** [comment]
I will try that. Thanks

**Comment by J-Calvelo** [comment]
I couldn't try it because the computer I usually work on is not mine, but managed to install it in another with pip3.
It seems that the pre python2 decommissioning Ubuntu version and extensive use of conda have done a mess.
Anyway, thanks!
