### ISSUE TITLE
Explanation of hreshold free approach?

### ISSUE THREAD

**Issue by charlesfoster** [niemasd/TreeCluster#6]
Hi there,

I'm interested in trying out the threshold-free approach of TreeCluster, but I can't seem to figure out what the command should be. Could you please assist?

Running TreeCluster normally, I've successfully used the following:

```
TreeCluster.py -t 0.0001 -i mytree.tre
```

Using the threshold-free approach, I've tried:

```
TreeCluster.py -i mytree.tre  --threshold_free
```
Output: "TreeCluster.py: error: argument -tf/--threshold_free: expected one argument"

```
TreeCluster.py -i mytree.tre  --threshold_free 5
```
Output: "TreeCluster.py: error: the following arguments are required: -t/--threshold"

```
TreeCluster.py -i mytree.tre  --threshold_free 5 -t 0.0001
```
Output: "AssertionError: ERROR: Invalid threshold-free approach: 5"

I'm stumped. What's the correct usage? Intuitively, I'd assume a threshold-free approach wouldn't require setting a threshold.

Thanks

**Comment by niemasd** [comment]
Thanks for reaching out! The `--threshold_free` option takes as its argument the threshold free approach, which currently only supports `argmax_clusters` (picks the threshold that maximizes the number of clusters). The `--threshold` (`-t`) argument in this case specifies the maximum threshold to try (I should update the documentation with examples). Example usage (the max threshold to try is 0.01):

```
TreeCluster.py -i mytree.tre  --threshold_free argmax_clusters -t 0.01
```

**Comment by charlesfoster** [comment]
Yep, that worked. Thanks for the explanation!

**Comment by niemasd** [comment]
No problem, glad to hear it! 😄
