### ISSUE TITLE
Definition of branch support

### ISSUE THREAD

**Issue by NakarinP** [niemasd/TreeCluster#7]
Hi Dr.Moshiri,

Thanks for developing this tool. It's very useful for our work (defining clusters). However, the definition of branch support threshold (-s) is not clear to me. You described that "no pair of leaves in any cluster can be connected by branches with support less than or equal to s". Does this mean **every branch (or node) within the defined cluster** must have the support more than s? Or it means **only ancestral branch (or node) of the defined cluster** must have the support more than s. For our study, we need only the ancestral node to have a high support.

Thank you in advance for clarifying,

Nakarin

**Comment by niemasd** [comment]
Thanks for reaching out, and great question! It is the first definition you listed: ***all*** branches within the defined cluster must have a support more than *s*. We unfortunately don't have the second definition implemented, in which only the ancestral branch must have high support

**Comment by NakarinP** [comment]
Thank you!

**Comment by niemasd** [comment]
No problem! Thank you for using our tool 😄

**Comment by NakarinP** [comment]
Sorry for bothering again,

Is it possible to add such a function (only the ancestral branch must have high support) into the python script? Or do you have any suggestion for incorporating that with the original TreeCluster script.

Thank you!

Nakarin

**Comment by niemasd** [comment]
I unfortunately don't think it would be simple ☹️ The current way we implement the "all branches must have at least *x* support" functionality is by preprocessing the tree by iterating over all branches in the tree and setting all branches with < *x* support to have a length of infinity (which fails all of the clustering objective functions we currently implement)

**Comment by NakarinP** [comment]
Thank you for the clear explanation, I appreciate that.

**Comment by niemasd** [comment]
No problem, and sorry I couldn't be more help!
