### ISSUE TITLE
I am facing some issue 

### ISSUE THREAD

**Issue by ankeetkumar** [niemasd/TreeCluster#9]
I am getting an error which I am not able to understand " File /usr/local/lib/python3.8/dist-packages/treeswift/Tree.py", line 1455, in read_tree_newick raise RuntimeError("Failed to parse string as Newick: %s"%ts) 

Please help me troubleshoot this.

Thanks

**Comment by niemasd** [comment]
Can you provide more context about the error? E.g. the complete error message with full stack trace, and ideally the exact commands + files you used to produce it? This error message implies that an invalid Newick strings was attempted to be read

**Comment by niemasd** [comment]
I'm going to go ahead and close this GitHub Issue due to inactivity, but please feel free to reopen it when you have more information that you can provide.
